# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Web-DJWidgets
version:      0.1
version_from: DJWidgets.pm
installdirs:  site
requires:
    Test::Deep:                    0.082
    Test::More:                    0.47
    WWW::FieldValidator:           1.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
